In [0]:
import torch
import numpy as np

import pandas as pd

# Trabajando con tensores

---



In [2]:
torch.__version__

'1.1.0'

In [4]:
tensor_a = torch.ones(2, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [7]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)

tensor([[9.5236e-37, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])


tensor([[0.6485, 0.8385],
        [0.5886, 0.3078]])

In [9]:
tensor_c = torch.rand(2, 2)
tensor_c

tensor([[0.1201, 0.4442],
        [0.8258, 0.4331]])

In [10]:
result = tensor_b + tensor_c
result

tensor([[0.7686, 1.2827],
        [1.4143, 0.7409]])

In [13]:
result.shape
reshaped = result.view(4,1)
reshaped

tensor([[0.7686],
        [1.2827],
        [1.4143],
        [0.7409]])

In [20]:
points = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(points)
points[0][1] = 2.5
print(points)
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [22]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

In [25]:
p_t = points.t()
p_t, p_t.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

In [28]:
tensor_x = torch.tensor([1, 2, 3, 4])
#tensor_x, torch.unsqueeze(tensor_x, 0)
tensor_x, torch.unsqueeze(tensor_x, 1)



(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [34]:
numpyArray = np.random.randn(2,2)

from_numpy = torch.from_numpy(numpyArray)
from_numpy


tensor([[-1.2642,  1.5120],
        [-1.8437, -0.6119]], dtype=torch.float64)

# Representar datos con tensores

---



In [37]:
print(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([[-1.2642,  1.5120],
        [-1.8437, -0.6119]], dtype=torch.float64)
tensor(-0.5519, dtype=torch.float64)
tensor([-1.5539,  0.4501], dtype=torch.float64)
tensor([ 0.1239, -1.2278], dtype=torch.float64)


In [38]:
torch.std(from_numpy, dim=1)

tensor([1.9631, 0.8710], dtype=torch.float64)

In [0]:
torch.save(from_numpy, 'tensor.t')

In [40]:
load = torch.load('tensor.t')
load

tensor([[-1.2642,  1.5120],
        [-1.8437, -0.6119]], dtype=torch.float64)

In [43]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
5               5  183277  ...        8.0         €172.1M
6               6  177003  ...        9.0         €137.4M
7               7  176580  ...       37.0           €164M
8               8  155862  ...       11.0         €104.6M
9               9  200389  ...       89.0         €144.5M
10             10  188545  ...       10.0         €127.1M
11             11  182521  ...       10.0         €156.8M
12             12  182493  ...       15.0          €90.2M
13             13  168542  ...       12.0           €111M
14             14  215914  ...       10.0         €121.3M
15             15  211110  ...        8.0         €153.5M
16             16  202126  ...       11.0         €160.7M
17             17  194765  ...       14.0         €165.8M
18             18  192448  ...       90.0         €123.3M
19             19  192119  ...       88.0         €113.7M
20             20  189511  ...       13.0         €105.6M
21             21  179813  ...       10.0           €111M
22             22  167495  ...       87.0          €62.7M
23             23  153079  ...       14.0         €119.3M
24             24  138956  ...        3.0          €44.6M
25             25  231747  ...        6.0         €166.1M
26             26  209331  ...       14.0         €137.3M
27             27  200145  ...       12.0         €126.4M
28             28  198710  ...       14.0             NaN
29             29  198219  ...       10.0         €105.4M
...           ...     ...  ...        ...             ...
18177       18177  238550  ...       12.0           €193K
18178       18178  243158  ...       51.0            €94K
18179       18179  246243  ...        8.0           €119K
18180       18180  221669  ...       45.0            €78K
18181       18181  245734  ...       10.0           €109K
18182       18182  246001  ...        6.0           €101K
18183       18183   53748  ...       46.0             NaN
18184       18184  241657  ...       15.0            €78K
18185       18185  243961  ...        8.0            €88K
18186       18186  240917  ...        8.0           €167K
18187       18187  240158  ...       12.0            €66K
18188       18188  240927  ...       10.0           €143K
18189       18189  240160  ...        8.0           €125K
18190       18190  245569  ...        8.0           €165K
18191       18191  245570  ...       12.0           €119K
18192       18192  245571  ...       13.0           €119K
18193       18193  244823  ...       11.0            €99K
18194       18194  245862  ...       44.0           €109K
18195       18195  243582  ...       13.0           €153K
18196       18196  238477  ...        8.0           €113K
18197       18197  246167  ...       15.0            €88K
18198       18198  242844  ...       48.0           €165K
18199       18199  244677  ...       15.0           €175K
18200       18200  231381  ...       11.0           €143K
18201       18201  243413  ...       13.0           €153K
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [44]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [50]:
subset = dataframe[['Overall','Age','International Reputation', 'Weak Foot',
       'Skill Moves' ]].dropna(axis=0, how='any')

columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [0]:
data = players[:, 1:]
data, data.shape

In [52]:
target = players[:, 0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [53]:
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [54]:
std = torch.std(data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [55]:
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [58]:
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
notSoGood = data[torch.le(target, 70)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
notSoGoodMean = torch.mean(notSoGood, dim=0)

# goodMean, averageMean, notSoGoodMean

for i, args in enumerate(zip(columns, goodMean, averageMean, notSoGoodMean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
